# Generated by Django 6.1.1 on 2026-09-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('latest_report', models.JSONField(blank=True, null=True)),
                ('latest_heartbeat', models.JSONField(blank=True, null=True)),
                ('latest_performance', models.JSONField(blank=True, null=True)),
                ('latest_processes', models.JSONField(blank=True, null=True)),
                ('latest_services', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
