# Generated by Django 6.1.1 on 2026-10-08 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_project_app', '0003_computer_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='token_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='hostname',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='computer',
            constraint=models.UniqueConstraint(fields=('owner', 'hostname'), name='unique_hostname_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='computer',
            constraint=models.UniqueConstraint(condition=models.Q(('token_hash__isnull', True)), fields=('hostname',), name='unique_hostname_until_enrolled'),
        ),
        migrations.AddField(
            model_name='enrollmentcode',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='senior_project_app.computer'),
        ),
        migrations.AddField(
            model_name='enrollmentcode',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
